"""Shared business constants for EasyFlex Web."""

STARTING_CREDITS = 20
PDF_INVOICE_CREDIT_COST = 1
TABLE_UPLOAD_CREDIT_COST = 5
PRICE_PER_CREDIT = 0.5
MIN_CREDIT_PURCHASE = 100

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 200

DEFAULT_MAX_UPLOAD_BYTES = 256 * 1024 * 1024
DEFAULT_MAX_PDF_FILES_PER_BATCH = 100
DEFAULT_MAX_PDF_FILE_BYTES = 25 * 1024 * 1024
DEFAULT_MAX_BATCH_TOTAL_BYTES = 250 * 1024 * 1024
DEFAULT_MAX_BATCH_TOTAL_PAGES = 500
DEFAULT_MAX_TABLE_FILE_BYTES = 32 * 1024 * 1024
DEFAULT_MAX_TABLE_SYNC_ROWS = 2000

JOB_TYPE_EXTRACT_PDF = "extract_pdf"
JOB_TYPE_IMPORT_ABRA = "import_abra"

JOB_STATUS_QUEUED = "queued"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_COMPLETED_WITH_ERRORS = "completed_with_errors"
JOB_STATUS_RETRYABLE_FAILED = "retryable_failed"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_CANCELLED = "cancelled"

JOB_TERMINAL_STATUSES = {
	JOB_STATUS_COMPLETED,
	JOB_STATUS_COMPLETED_WITH_ERRORS,
	JOB_STATUS_FAILED,
	JOB_STATUS_CANCELLED,
}

JOB_STATUS_LABELS = {
	JOB_STATUS_QUEUED: "Ve frontě",
	JOB_STATUS_RUNNING: "Zpracovává se",
	JOB_STATUS_COMPLETED: "Dokončeno",
	JOB_STATUS_COMPLETED_WITH_ERRORS: "Dokončeno s chybami",
	JOB_STATUS_RETRYABLE_FAILED: "Čeká na retry",
	JOB_STATUS_FAILED: "Selhalo",
	JOB_STATUS_CANCELLED: "Zrušeno",
}

BATCH_STATUS_QUEUED = "queued"
BATCH_STATUS_RUNNING = "running"
BATCH_STATUS_WAITING_IMPORT = "waiting_import"
BATCH_STATUS_IMPORTING = "importing"
BATCH_STATUS_COMPLETED = "completed"
BATCH_STATUS_COMPLETED_WITH_ERRORS = "completed_with_errors"
BATCH_STATUS_PARTIAL_TIMEOUT = "partial_timeout"
BATCH_STATUS_INTERRUPTED = "interrupted"
BATCH_STATUS_FAILED = "failed"

BATCH_TERMINAL_STATUSES = {
	BATCH_STATUS_COMPLETED,
	BATCH_STATUS_COMPLETED_WITH_ERRORS,
	BATCH_STATUS_PARTIAL_TIMEOUT,
	BATCH_STATUS_INTERRUPTED,
	BATCH_STATUS_FAILED,
}

BATCH_STATUS_LABELS = {
	BATCH_STATUS_QUEUED: "Ve frontě",
	BATCH_STATUS_RUNNING: "Zpracovává se",
	BATCH_STATUS_WAITING_IMPORT: "Čeká na import",
	BATCH_STATUS_IMPORTING: "Importuje se",
	BATCH_STATUS_COMPLETED: "Dokončeno",
	BATCH_STATUS_COMPLETED_WITH_ERRORS: "Dokončeno s chybami",
	BATCH_STATUS_PARTIAL_TIMEOUT: "Částečný výsledek (časový limit)",
	BATCH_STATUS_INTERRUPTED: "Vyžaduje zásah",
	BATCH_STATUS_FAILED: "Selhalo",
}

BATCH_PHASE_LABELS = {
	"queued": "Ve frontě",
	"initializing": "Inicializace",
	"extracting": "Extrakce PDF",
	"persisting": "Ukládání výsledků",
	"waiting_import": "Čeká na import",
	"importing": "Import do ABRA",
	"finalizing": "Dokončení dávky",
	"done": "Hotovo",
}

ROW_IMPORT_STATUS_PENDING = "pending"
ROW_IMPORT_STATUS_RUNNING = "running"
ROW_IMPORT_STATUS_IMPORTED = "imported"
ROW_IMPORT_STATUS_SKIPPED = "skipped"
ROW_IMPORT_STATUS_FAILED = "failed"
